#!/bin/bash
echo The first argument is $1
echo The Second argument is $2
echo The Third argument is $3

echo \$ $$ PID of the script
echo \# $# count arguments
echo \? $? last return code
echo \* $* all the arguments
echo this is script is called $0
