#!/bin/bash
echo -n "Enter a number: "
read num1
if [ $num1 -lt 1 -o $num1 -gt 100  ]
then echo Wrong number...
exit 1
fi
echo -n "Enter another number:"
read num2
if [ $num2 -lt 1 -o $num2 -gt 100  ]
then echo Wrong number...
exit 2
fi

let tong="$num1 + $num2"
let tich="$num1 * $num2"
echo -e "Sum: $num1 + $num2 = $tong"
echo -e "Product: $num1 * $num2 = $tich"

(( $tong == $tich )) && echo CONGRADTULATION!! 
